### ISSUE TITLE
请求签名密钥配置功能

### ISSUE THREAD

**Issue by qiyueshiyi** [idarex/pingpp-yii2#17]
找了半天没找到.
每次请求还要, 手动设置一遍, `\Pingpp\Pingpp::setPrivateKeyPath('path/to/rsa_private_key.pem')`

> 好麻烦哦

能不能初始化的时候就设置好!!!

**Comment by dcb9** [comment]
刚才看了一下这个功能，我用之前还没有这个功能呢。有兴趣尝试实现一下这个功能吗？ 估计五月会再抽出一点时间来更新一些新的功能。

# 设置请求签名密钥

> 密钥需要你自己生成，公钥请填写到 Ping++ Dashboard
> \Pingpp\Pingpp::setPrivateKeyPath('/path/to/your_rsa_private_key.pem');

**Comment by dcb9** [comment]
添加请求签名密钥配置功能 8591490524df32975e60057c5e6e0331f0da8f8b
Add configuring RSA private key 64b091103b7b2db90a642dfddebab7c05a12c83d

**Comment by dcb9** [comment]
刚才提前发布了一版 [v1.2-alpha](https://github.com/idarex/pingpp-yii2/releases/tag/v1.2-alpha) 欢迎测试
