### ISSUE TITLE
测试失败。

### ISSUE THREAD

**Issue by neatlife** [idarex/pingpp-yii2#2]
PHP Fatal error:  Class 'idarex\pingppyii2\Charge' not found in .../pingpp-yii2/tests/PingppComponentTest.php on line 32

Fatal error: Class 'idarex\pingppyii2\Charge' not found in .../pingpp-yii2/tests/PingppComponentTest.php on line 32

**Comment by dcb9** [comment]
谢谢，已经改正！

现在公司业务比较忙，功能和测试都还不全，欢迎提 PR 过来！
