### ISSUE TITLE
packagist.org上的dev-master分支的代码不是最新，请尽快更新成最新代码。

### ISSUE THREAD

**Issue by neatlife** [idarex/pingpp-yii2#4]

**Comment by dcb9** [comment]
好奇怪 Auto updated 的 Hooks 在 Github 这边已经设置好了，但是 packgist.org 那完全就收不到，Github 这边在测试的时间说已经测试通过了。。

**Comment by neatlife** [comment]
刚才我试着执行
composer clearcache
composer update idarex/pingpp-yii2
更新下来了最新的包😂。
我猜测可能是composer的缓存机制有bug😂。

**Comment by dcb9** [comment]
因为现在功能还不全，所以还没有准备好发 1.0，准备周末有空的话把基本功能做完，然后发一版本。

**Comment by neatlife** [comment]
👍

**Comment by dcb9** [comment]
添加了需要做的功能列表，可以帮忙实现几个功能 :) [功能列表](https://github.com/idarex/pingpp-yii2#使用)

**Comment by neatlife** [comment]
👌
